Repository Todak-Padak/TodakTodak_backend, pull requests merged in 2024-10, with the labels that each got.

#122 FE: 회원 로그인, 카카오 로그인, 의사 이메일 찾기, 의사 로그인, 비밀번호 재설정 링크 전송 및 재설정
  member/src/main/java/com/padaks/todaktodak/common/service/InitialDataLoader.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/AdminSaveDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberFindPasswordDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberSaveReqDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/PasswordResetDto.java
  member/src/main/java/com/padaks/todaktodak/member/service/CustomOAuth2UserService.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  member/src/main/java/com/padaks/todaktodak/member/service/OAuthAttributes.java
  reservation/src/main/resources/application.yml
Labels: 기능 구현, 기능 수정

#124 feat: 프론트 작업을 위한 백엔드 수정
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/service/CustomOAuth2UserService.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentFailDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentSuccessDto.java
  member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/KafkaReservationConsumerConfig.java
  reservation/src/main/resources/application.yml
Labels: 기능 수정

#126 feat: redis 조회수, 좋아요
  community/src/main/java/com/padaks/todaktodak/common/config/RedisConfigs.java
  community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
  community/src/main/java/com/padaks/todaktodak/post/domain/Post.java
  community/src/main/java/com/padaks/todaktodak/post/dto/PostDetailDto.java
  community/src/main/java/com/padaks/todaktodak/post/dto/PostListDto.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
  community/src/main/resources/application.yml
  member/src/main/java/com/padaks/todaktodak/common/kafka/KafkaConsumerConfig.java
Labels: 기능 구현

#129 Feat/is 101 예약 노쇼 카운트 스케줄러 구현
  member/src/main/java/com/padaks/todaktodak/MemberApplication.java
  member/src/main/java/com/padaks/todaktodak/common/config/FeignConfig.java
  member/src/main/java/com/padaks/todaktodak/common/feign/ReservationFeignClient.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
Labels: 기능 구현

#138 feat/IS-110 fix : 커뮤니티 답변 권한관리, 삭제 권한관리, 게시글/답변 삭제 후 리스트 조회 불가
  community/src/main/java/com/padaks/todaktodak/comment/repository/CommentRepository.java
  community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
  community/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignDto.java
  community/src/main/java/com/padaks/todaktodak/post/repository/PostRepository.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
Labels: 기능 수정

#139 feat: 결제 알림 및 커뮤니티 알림 로직 수정 및 memberEmail 코드로 변경
  member/src/main/java/com/padaks/todaktodak/member/controller/FcmController.java
  member/src/main/java/com/padaks/todaktodak/member/service/FcmService.java
  member/src/main/java/com/padaks/todaktodak/notification/domain/Type.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelFailDto.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
  member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
Labels: 기능 구현, 기능 수정

#143 Feat/is-114 신고5회 커뮤니티 사용제한
  community/src/main/java/com/padaks/todaktodak/comment/controller/CommentController.java
  community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
  community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberPayDto.java
Labels: 기능 수정

#145 IS-118 fix : 의사 근무시간 중복 등록 방지 변경
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/repository/DoctorOperatingHoursRepository.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java
Labels: 기능 수정

#146 feat/IS-119feat: 채팅 메세지 전송시 상대방에게 알림 전송
  member/src/main/java/com/padaks/todaktodak/chat/service/ChatKafkaListener.java
  member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java
  member/src/main/java/com/padaks/todaktodak/notification/domain/Type.java
Labels: 기능 구현

#141 #140 feat : 당일 예약, 스케줄 예약 성공 및 실패 시 알람 설정(알람 미구현)
  member/src/main/java/com/padaks/todaktodak/common/kafka/ReservationKafkaConsumerConfig.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/ReservationSuccessResDto.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
Labels: 기능 구현

#137 #136 feat : 예약 시간 30분전 Kafka 메시지 전송 로직 구현 (알림 수신 로직 구현 X)
  member/src/main/java/com/padaks/todaktodak/notification/dto/ReserveBeforeNotifyResDto.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
Labels: 기능 구현

#150 feat: 나의 리뷰 리스트
  reservation/src/main/java/com/padaks/todaktodak/review/controller/ReviewController.java
  reservation/src/main/java/com/padaks/todaktodak/review/domain/Review.java
  reservation/src/main/java/com/padaks/todaktodak/review/dto/ReviewMyListResDto.java
  reservation/src/main/java/com/padaks/todaktodak/review/repository/ReviewRepository.java
  reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java
Labels: 기능 구현

#151 Fix/IS-126 의사 근무 시간 설정 수정
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/controller/DoctorOperatingHoursController.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/domain/DoctorOperatingHours.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursReqDto.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursSimpleResDto.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java
Labels: 기능 수정

#152 feat: myReviewList deletedAtNull
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  reservation/src/main/java/com/padaks/todaktodak/review/domain/Review.java
  reservation/src/main/java/com/padaks/todaktodak/review/dto/ReviewMyListResDto.java
  reservation/src/main/java/com/padaks/todaktodak/review/dto/ReviewSaveReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/review/repository/ReviewRepository.java
  reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java
Labels: 기능 구현

#153 feat/IS-130/feat: 병원별 의사 목록 조회
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/DoctorListResDto.java
  member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 구현

#154 Revert "feat/IS-130/feat: 병원별 의사 목록 조회"
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/DoctorListResDto.java
  member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 수정

#155 IS-131/feat: 로그인한 사용자 신고횟수 조회
  gateway/.DS_Store
  gateway/src/main/resources/application-local.yml
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 구현

#156 IS-130/chore: 의사 근무시간 정보 추가
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/DoctorListResDto.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 구현, 기능 수정

#157 Feat/is 133 findByRoleAndHospitalId 추가
  member/src/main/java/com/padaks/todaktodak/chat/service/ChatKafkaListener.java
  member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java
  member/src/main/java/com/padaks/todaktodak/member/controller/FcmController.java
  member/src/main/java/com/padaks/todaktodak/member/repository/DelMemberRepository.java
  member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
  member/src/main/java/com/padaks/todaktodak/member/service/FcmService.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
  member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java
Labels: 내부설정 수정

#159 feat: 의사별 대면&&비대면, 대면, 비대면, 리뷰디테일 추가 + 리뷰 작성자 이름 마스킹 처리
  reservation/src/main/java/com/padaks/todaktodak/review/controller/ReviewController.java
  reservation/src/main/java/com/padaks/todaktodak/review/domain/Review.java
  reservation/src/main/java/com/padaks/todaktodak/review/dto/ReviewListResDto.java
  reservation/src/main/java/com/padaks/todaktodak/review/dto/ReviewSaveReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/review/repository/ReviewRepository.java
  reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java
Labels: 기능 구현, 기능 수정

#160 IS-136/fix: doctorListByHospital 추가
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
Labels: 기능 수정

#161 Fix/is-139 게시판 사용자 이름 정보 추가
  community/src/main/java/com/padaks/todaktodak/comment/dto/CommentDetailDto.java
  community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
  community/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignDto.java
  community/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignNameDto.java
  community/src/main/java/com/padaks/todaktodak/common/feign/MemberFeignClient.java
  community/src/main/java/com/padaks/todaktodak/post/dto/PostDetailDto.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberFeignNameDto.java
Labels: 기능 수정

#162 feat: 커뮤니티 사용자 마스킹 처리, feign dto 수정
  community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
  community/src/main/java/com/padaks/todaktodak/post/domain/Post.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
  reservation/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignDto.java
  reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java
Labels: 기능 구현, 기능 수정

#164 feat: 회원 사진 업데이트
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 구현, 기능 수정

#166 fix/IS-139 fix: commentList 부모 comment 정보, 생성/수정시간 추가
  community/src/main/java/com/padaks/todaktodak/comment/dto/CommentDetailDto.java
  community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
Labels: 기능 수정

#170 bug: 결제 카프카 역직렬화 오류 수정
  member/src/main/java/com/padaks/todaktodak/common/kafka/KafkaConsumerConfig.java
  member/src/main/java/com/padaks/todaktodak/member/service/CustomOAuth2UserService.java
  member/src/main/java/com/padaks/todaktodak/member/service/FcmService.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelFailDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentFailDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentSuccessDto.java
  member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java
  reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
Labels: 기능 수정

#172 feat/IS-165 fix: PostList postImgUrl 추가
  community/src/main/java/com/padaks/todaktodak/post/domain/Post.java
  community/src/main/java/com/padaks/todaktodak/post/dto/PostListDto.java
Labels: 기능 수정

#173 feat: 알림 코드 전체적인 수정 및 카프카 오류 해결, 자녀 공유 알림 추가, 알림 클릭시 읽음 처리와 해당 페이지 이동 로직
  member/src/main/java/com/padaks/todaktodak/chat/service/ChatKafkaListener.java
  member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java
  member/src/main/java/com/padaks/todaktodak/common/config/AppConfig.java
  member/src/main/java/com/padaks/todaktodak/common/config/WebConfig.java
  member/src/main/java/com/padaks/todaktodak/common/kafka/KafkaConsumerConfig.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberLoginDto.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  member/src/main/java/com/padaks/todaktodak/notification/controller/FcmController.java
  member/src/main/java/com/padaks/todaktodak/notification/controller/NotificationController.java
  member/src/main/java/com/padaks/todaktodak/notification/domain/FcmNotification.java
  member/src/main/java/com/padaks/todaktodak/notification/domain/Type.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/ChildSuccessResDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationReqDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationResDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelFailDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentFailDto.java
  member/src/main/java/com/padaks/todaktodak/notification/repository/NotificationRepository.java
  member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationService.java
  member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
Labels: 기능 구현, 기능 수정, 내부설정 수정

#174 feat: post list 이미지와 조회수, 좋아요 표시 및 조회수, 좋아요 12시간마다 db저장(스케줄러)
  community/src/main/java/com/padaks/todaktodak/CommunityApplication.java
  community/src/main/java/com/padaks/todaktodak/post/domain/Post.java
  community/src/main/java/com/padaks/todaktodak/post/dto/PostDetailDto.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostBatchService.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
  reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
Labels: 기능 구현, 기능 수정

#175 feat: 나의 게시글 목록
  community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
  community/src/main/java/com/padaks/todaktodak/post/repository/PostRepository.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
Labels: 기능 구현

#178 feat: 캘린더 데이터를 위한 예약 리스트
  community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
Labels: 기능 수정

#179 Feat/IS-175: 신고 처리 상태 추가
  community/src/main/java/com/padaks/todaktodak/report/controller/ReportController.java
  community/src/main/java/com/padaks/todaktodak/report/domain/Report.java
  community/src/main/java/com/padaks/todaktodak/report/domain/Status.java
  community/src/main/java/com/padaks/todaktodak/report/dto/ReportListResDto.java
  community/src/main/java/com/padaks/todaktodak/report/dto/ReportSaveReqDto.java
  community/src/main/java/com/padaks/todaktodak/report/service/ReportService.java
Labels: 기능 구현

#180 Feat/is 172 의사 정보 : 의사 이름, 사진, 병원 명, 예약수, 리뷰수 조회
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
  member/src/main/java/com/padaks/todaktodak/common/dto/CheckHospitalListReservationReqDto.java
  member/src/main/java/com/padaks/todaktodak/common/dto/DoctorInfoDto.java
  member/src/main/java/com/padaks/todaktodak/common/dto/HospitalInfoDto.java
  member/src/main/java/com/padaks/todaktodak/common/dto/ReviewDetailDto.java
  member/src/main/java/com/padaks/todaktodak/common/feign/ReservationFeignClient.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/dto/ReservationFeignDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/ReviewListResDto.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/dto/CheckHospitalListReservationReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalInfoDto.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/dto/ReservationFeignDto.java
Labels: 기능 구현

#184 FIX/IS-185 fix: 커뮤니티 사진 없이 게시글 등록 가능
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
Labels: 기능 수정

#186 feat: 캘린더를 위한 백엔드 작업 event 테이블 추가
  member/src/main/java/com/padaks/todaktodak/event/controller/EventController.java
  member/src/main/java/com/padaks/todaktodak/event/domain/Event.java
  member/src/main/java/com/padaks/todaktodak/event/domain/Type.java
  member/src/main/java/com/padaks/todaktodak/event/dto/EventCreateReqDto.java
  member/src/main/java/com/padaks/todaktodak/event/dto/EventDetailResDto.java
  member/src/main/java/com/padaks/todaktodak/event/dto/EventListResDto.java
  member/src/main/java/com/padaks/todaktodak/event/dto/EventUpdateReqDto.java
  member/src/main/java/com/padaks/todaktodak/event/repository/EventRepository.java
  member/src/main/java/com/padaks/todaktodak/event/service/EventService.java
Labels: 기능 구현

#187 Feat/IS-188: 의료 정보 api 받아오기
  member/src/main/java/com/padaks/todaktodak/child/service/ChildService.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/dto/ReservationSaveResDto.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
Labels: 기능 구현

#189 feat: 캘린더 작업을 위한 수정
  member/src/main/java/com/padaks/todaktodak/event/domain/Event.java
  member/src/main/java/com/padaks/todaktodak/event/domain/Type.java
  member/src/main/java/com/padaks/todaktodak/event/service/EventService.java
Labels: 기능 수정

#193 Feat/IS-205: 병원 측 예약리스트 api 수정
  reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckHospitalListReservationReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckHospitalListReservationResDto.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java
Labels: 기능 수정

#196 feat: 캘린더 구글 공휴일 api, rservation 이슈 있을지도..?
  member/build.gradle
  member/src/main/java/com/padaks/todaktodak/event/controller/EventController.java
  member/src/main/java/com/padaks/todaktodak/event/controller/GoogleCalendarProxyController.java
  reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
Labels: 기능 구현, 기능 수정

#197 chore: 구글 맵 api key 재발급 및 숨김 처리
  member/src/main/java/com/padaks/todaktodak/event/controller/GoogleCalendarProxyController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
Labels: 기능 수정, 내부설정 수정

#199 feat: 알림 url 수정 및 카프카 ack 처리
  member/src/main/java/com/padaks/todaktodak/child/domain/Child.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/notification/controller/FcmController.java
  member/src/main/java/com/padaks/todaktodak/notification/domain/FcmNotification.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationResDto.java
  member/src/main/java/com/padaks/todaktodak/notification/repository/NotificationRepository.java
  member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
Labels: 기능 수정

#202 feat: 알림 페이지네이션,title body 분리 및 자잘한 수정
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberListResDto.java
  member/src/main/java/com/padaks/todaktodak/notification/controller/FcmController.java
  member/src/main/java/com/padaks/todaktodak/notification/domain/FcmNotification.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationReqDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationResDto.java
  member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java
Labels: 기능 수정, 내부설정 수정

#205 Fix/is 227
  community/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignDto.java
  community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
  community/src/main/java/com/padaks/todaktodak/post/dto/PostDetailDto.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberPayDto.java
Labels: 기능 수정

#207 feat: 멤버리스트 수정
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberListResDto.java
  member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 수정, 내부설정 수정

#210 feat: 관리자 병원 페이지를 위한 백엔드 작업
  reservation/src/main/java/com/padaks/todaktodak/hospital/adminDto/AdminHospitalListDetailResDto.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/repository/HospitalRepository.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
Labels: 기능 구현

#211 Feat/IS-241 병원 관리자 의사 삭제 | 병원별 의사목록, 삭제된 의사 조회 불가 | 의사 리스트 조회, 인증 여부 추가
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/DoctorDeleteDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/DoctorListResDto.java
  member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 구현

#212 feat: 정기 결제 로직과 데이터 수정(DB -> 사업자 번호 추가)
  reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
  reservation/src/main/java/com/padaks/todaktodak/payment/domain/Pay.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/PaymentMemberResDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/PaymentReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/PaymentSuccessDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
Labels: 기능 수정

#216 Fix/is 173 : 병원리스트조회(정렬조건 : 거리가까운순, 리뷰개수 순, 리뷰평점순)
  reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/domain/Hospital.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalListResDto.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalUpdateReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java
Labels: 기능 구현, 기능 수정

#215 feat: 정기결제 및 병원 관리자 role 추가, 새로운 토큰 발급 및 갱신
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Role.java
  member/src/main/java/com/padaks/todaktodak/member/dto/HospitalAdminSaveReqDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberDetailResDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberResDetailDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/PaymentSuccessDto.java
  member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  reservation/src/main/java/com/padaks/todaktodak/common/domain/Role.java
  reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
Labels: 기능 구현, 기능 수정

#218 feat: 의사 비대면 리스트 평균 평점
  reservation/src/main/java/com/padaks/todaktodak/review/controller/ReviewController.java
  reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java
Labels: 기능 구현

#219 fix/IS-260 fix: 의사 휴게시간 병원 휴게시간으로 자동설정
  member/src/main/java/com/padaks/todaktodak/common/enumdir/DayOfHoliday.java
  member/src/main/java/com/padaks/todaktodak/common/feign/ReservationFeignClient.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/domain/DoctorOperatingHours.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursReqDto.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursResDto.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java
  member/src/main/java/com/padaks/todaktodak/member/dto/HospitalOperatingHoursResDto.java
  reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/controller/HospitalOperatingHoursController.java
Labels: 기능 수정

#222 feat: 결제 리스트(검색, 필터링)
  reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
  reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
  reservation/src/main/java/com/padaks/todaktodak/payment/repository/PaymentRepository.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
Labels: 기능 수정

#223 feat: cs 리스트 검색 및 필터링
  member/src/main/java/com/padaks/todaktodak/chat/cs/controller/CsController.java
  member/src/main/java/com/padaks/todaktodak/chat/cs/domain/Cs.java
  member/src/main/java/com/padaks/todaktodak/chat/cs/dto/CsListResDto.java
  member/src/main/java/com/padaks/todaktodak/chat/cs/repository/CsRepository.java
  member/src/main/java/com/padaks/todaktodak/chat/cs/service/CsService.java
Labels: 기능 구현

#229 feat: 병원어드민 영업시간관리 백엔드
  reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/controller/HospitalOperatingHoursController.java
  reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/repository/HospitalOperatingHoursRepository.java
  reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/service/HospitalOperatingHoursService.java
Labels: 기능 수정

#230 feat: postBatch에서 create모드시 redis에서 없는 key 조회하는 에러 해결
  community/src/main/java/com/padaks/todaktodak/post/service/PostBatchService.java
Labels: 기능 수정

#237 feat: 알림 내용 변경, typeUrl 수정
  member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
  member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java
Labels: 기능 수정

#239 feat: 병원어드민 병원리스트 deletedAtIsNull처리
  reservation/src/main/java/com/padaks/todaktodak/hospital/repository/HospitalRepository.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
Labels: 기능 수정

#241 Feat/IS-321 / 백엔드 리드미 1차 수정
  README.md
  기획서.md
Labels: 문서 작업

#247 feat: 권한 제어
  community/src/main/java/com/padaks/todaktodak/common/config/JwtAuthFilter.java
  community/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
  member/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
  member/src/main/java/com/padaks/todaktodak/member/Handler/OAuth2SuccessHandler.java
  member/src/main/java/com/padaks/todaktodak/member/service/OAuthAttributes.java
  member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java
  reservation/src/main/java/com/padaks/todaktodak/common/config/JwtAuthFilter.java
  reservation/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
Labels: 기능 구현, 기능 수정

#250 feat: 권한관리 및 채팅
  community/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
  member/src/main/java/com/padaks/todaktodak/MemberApplication.java
  member/src/main/java/com/padaks/todaktodak/chat/controller/ChatController.java
  member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java
  member/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
  reservation/src/main/java/com/padaks/todaktodak/common/config/JwtAuthFilter.java
  reservation/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
Labels: 기능 수정

#255 feat: 토닥/병원 관계자 로그인 분리 및 예외 처리 구체화
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 수정

#262 feat: 알림 수정 및 k8s 배포 스크립트
  .github/workflows/todak_msa_k8s.yml
  community/k8s/community_depl.yml
  community/k8s/community_service.yml
  community/src/main/resources/application-dev.yml
  k8s/ConfigMap.yml
  k8s/certificate.yml
  k8s/ingress.yml
  member/k8s/member_depl.yml
  member/k8s/member_service.yml
  member/src/main/java/com/padaks/todaktodak/common/config/JwtAuthFilter.java
  member/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberLoginDto.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  member/src/main/java/com/padaks/todaktodak/notification/controller/FcmController.java
  member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java
  member/src/main/resources/application-dev.yml
  reservation/k8s/reservation_depl.yml
  reservation/k8s/reservation_service.yml
  reservation/src/main/resources/application-dev.yml
Labels: 기능 구현, 기능 수정

#264 feat: firebase 전체 수정
  member/.gitignore
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberLoginDto.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  reservation/.gitignore
  reservation/src/main/java/com/padaks/todaktodak/common/config/FirebaseConfig.java
Labels: 기능 수정, 내부설정 수정

#266 feat: fcm이슈
  member/src/main/java/com/padaks/todaktodak/common/config/FcmConfig.java
Labels: 내부설정 수정
