Repository Todak-Padak/TodakTodak_backend, pull requests merged in 2024-09, with the labels that each got.

#27 feat: 회원 이미지 업로드 -> 회원가입, 내 정보 수정
  member/build.gradle
  member/src/main/java/com/padaks/todaktodak/MemberApplication.java
  member/src/main/java/com/padaks/todaktodak/common/dto/CommonResDto.java
  member/src/main/java/com/padaks/todaktodak/config/JwtAuthFilter.java
  member/src/main/java/com/padaks/todaktodak/member/Handler/OAuth2SuccessHandler.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberSaveReqDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberUpdateReqDto.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 구현

#25 #23 feat : 병원 예약 list 출력 기능 구현
  reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckHospitalListReservationReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckHospitalListReservationResDto.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java
  reservation/src/test/java/com/padaks/todaktodak/ReservationListTest.java
Labels: 기능 구현

#26 Feat/is 15: 자녀 공유 기능 & 주민번호 암호화
  member/src/main/java/com/padaks/todaktodak/child/controller/ChildController.java
  member/src/main/java/com/padaks/todaktodak/child/dto/ChildRegisterResDto.java
  member/src/main/java/com/padaks/todaktodak/child/dto/ChildResDto.java
  member/src/main/java/com/padaks/todaktodak/child/dto/ChildShareReqDto.java
  member/src/main/java/com/padaks/todaktodak/child/repository/ChildRepository.java
  member/src/main/java/com/padaks/todaktodak/child/service/ChildService.java
  member/src/main/java/com/padaks/todaktodak/childparentsrelationship/repository/ChildParentsRelationshipRepository.java
  member/src/main/java/com/padaks/todaktodak/childparentsrelationship/service/ChildParentsRelationshipService.java
  member/src/main/java/com/padaks/todaktodak/common/service/AESUtil.java
Labels: 기능 구현

#31 Feat/is 29 예약 상태 수정 API 기능 구현
  reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/dto/UpdateStatusReservation.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java
Labels: 기능 구현

#32 Feat/is 24 진료 내역 등록/조회 API
  reservation/build.gradle
  reservation/src/main/java/com/padaks/todaktodak/common/dto/CommonErrorDto.java
  reservation/src/main/java/com/padaks/todaktodak/common/dto/CommonResDto.java
  reservation/src/main/java/com/padaks/todaktodak/common/exception/exceptionType/ReservationExceptionType.java
  reservation/src/main/java/com/padaks/todaktodak/medicalchart/controller/MedicalChartController.java
  reservation/src/main/java/com/padaks/todaktodak/medicalchart/dto/MedicalChartResDto.java
  reservation/src/main/java/com/padaks/todaktodak/medicalchart/dto/MedicalChartSaveReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/medicalchart/repository/MedicalChartRepository.java
  reservation/src/main/java/com/padaks/todaktodak/medicalchart/service/MedicalChartFeign.java
  reservation/src/main/java/com/padaks/todaktodak/medicalchart/service/MedicalChartService.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
Labels: 기능 구현

#33 Feat/is 31
  .github/workflows/deploy-server-with-compose.yml
  .gitignore
  Dockerfile
  member/src/main/java/com/padaks/todaktodak/config/AwsS3Configs.java
  workflows/deploy-server-with-compose.yml
  workflows/deploy-server-with-ec2.yml
Labels: 기능 구현

#36 chore: 서버 배포 3차 테스트
  Dockerfile
Labels: 기능 수정

#37 chore: 서버 배포 4차 테스트
  Dockerfile
Labels: 기능 수정

#38 chore: 서버 배포 5차 테스트
  Dockerfile
Labels: 기능 수정

#40 chore: 서버 배포 6차 테스트
  Dockerfile
Labels: 기능 수정

#41 chore: 서버 배포 7차 테스트
  Dockerfile
Labels: 기능 수정

#43 chore: 서버 배포 8차 테스트
  Dockerfile
Labels: 기능 수정

#45 chore: 서버 배포 9차 테스트
  .github/workflows/deploy-server-with-compose.yml
  .gitignore
  member/.gitignore
Labels: 기능 수정

#46 chore: 서버 배포 10차 테스트
  Dockerfile
Labels: 기능 수정

#47 chore: 서버 배포 11차 테스트
  .github/workflows/deploy-server-with-compose.yml
  Dockerfile
Labels: 기능 수정

#48 chore: 서버 배포 12차 테스트
  .github/workflows/deploy-server-with-compose.yml
Labels: 기능 수정

#49 chore: 서버 배포 13차 테스트
  member/src/main/resources/application.yml
Labels: 기능 수정

#50 Feat/is 31
  .github/workflows/deploy-server-with-compose.yml
  member/build.gradle
Labels: 기능 수정

#51 chore: 서버 배포 16차 테스트
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
Labels: 기능 수정

#52 chore: 서버 배포 17차 테스트
  member/src/main/resources/application.yml
Labels: 기능 수정

#53 chore: 서버 배포 18차 테스트
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 구현

#54 chore: 서버 배포 19차 테스트
  member/Dockerfile
Labels: 기능 수정

#55 chore: 서버 배포 20차 테스트
  .github/workflows/deploy-server-with-compose.yml
Labels: 기능 수정

#56 chore: reservation 개발 서버 배포 1차
  .github/workflows/deploy-server-with-compose.yml
  reservation/.gitignore
  reservation/Dockerfile
Labels: 기능 구현

#57 chore: reservation 개발 서버 배포 2차
  member/src/main/resources/application.yml
Labels: 기능 수정

#58 chore: reservation 개발 서버 배포 3차
  reservation/src/main/resources/application.yml
Labels: 기능 수정

#59 chore: reservation 개발 서버 배포 4차
  reservation/build.gradle
  reservation/src/main/java/com/padaks/todaktodak/ReservationApplication.java
Labels: 기능 수정

#60 chore: reservation 개발 서버 배포 5차
  reservation/src/main/java/com/padaks/todaktodak/common/controller/CommonController.java
Labels: 기능 수정

#66 Feat/is 38: webrtc 테스트용 코드 작성
  reservation/build.gradle
  reservation/src/main/java/com/padaks/todaktodak/ReservationApplication.java
  reservation/src/main/java/com/padaks/todaktodak/configs/CorsConfig.java
  reservation/src/main/java/com/padaks/todaktodak/untact/config/WebSocketConfig.java
  reservation/src/main/java/com/padaks/todaktodak/untact/controller/UntactController.java
  reservation/src/main/java/com/padaks/todaktodak/untact/domain/Room.java
  reservation/src/main/java/com/padaks/todaktodak/untact/domain/WebSocketMessage.java
  reservation/src/main/java/com/padaks/todaktodak/untact/dto/RoomRequest.java
  reservation/src/main/java/com/padaks/todaktodak/untact/service/RoomService.java
  reservation/src/main/java/com/padaks/todaktodak/untact/service/UntactService.java
  reservation/src/main/java/com/padaks/todaktodak/untact/socket/SignalHandler.java
  reservation/src/main/java/com/padaks/todaktodak/untact/util/Parser.java
  reservation/src/main/resources/application-dev.yml
Labels: 기능 구현

#68 IS-36/ feat: comment 생성, 조회
  community/src/main/java/com/padaks/todaktodak/comment/controller/CommontController.java
  community/src/main/java/com/padaks/todaktodak/comment/domain/Comment.java
  community/src/main/java/com/padaks/todaktodak/comment/dto/CommentSaveDto.java
  community/src/main/java/com/padaks/todaktodak/comment/dto/CommentUpdateReqDto.java
  community/src/main/java/com/padaks/todaktodak/comment/repository/CommentRepository.java
  community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
  community/src/main/java/com/padaks/todaktodak/common/config/RedisConfigs.java
  community/src/main/java/com/padaks/todaktodak/communitynotification/controller/SseController.java
  community/src/main/java/com/padaks/todaktodak/communitynotification/domain/Notification.java
  community/src/main/java/com/padaks/todaktodak/communitynotification/dto/NotificationListDto.java
  community/src/main/java/com/padaks/todaktodak/communitynotification/service/NotificationService.java
  community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
  reservation/gradle/eureka/src/main/resources/application.yml
Labels: 기능 구현

#70 IS-40feat: 대댓글
  community/src/main/java/com/padaks/todaktodak/comment/domain/Comment.java
  community/src/main/java/com/padaks/todaktodak/comment/dto/CommentSaveDto.java
  community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
Labels: 기능 구현

#72 feat/IS-32 : 병원List조회 api 구현
  hospital/build.gradle
  hospital/src/main/java/com/padaks/todaktodak/HospitalApplication.java
  hospital/src/main/java/com/padaks/todaktodak/common/enumdir/DayOfHoliday.java
  hospital/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
  hospital/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalDTO/HospitalListResDto.java
  hospital/src/main/java/com/padaks/todaktodak/hospital/repository/HospitalRepository.java
  hospital/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
  hospital/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/controller/HospitalOperatingHoursController.java
  member/src/main/java/com/padaks/todaktodak/MemberApplication.java
Labels: 기능 구현

#74 chore : Member도 eureka client 주석처리
  member/src/main/java/com/padaks/todaktodak/MemberApplication.java
Labels: 내부설정 수정

#75 feat: 결제 서비스 1차 구현
  hospital/build.gradle
  member/build.gradle
  member/src/main/java/com/padaks/todaktodak/MemberApplication.java
  member/src/main/java/com/padaks/todaktodak/config/JwtAuthFilter.java
  member/src/main/java/com/padaks/todaktodak/config/SecurityConfig.java
  member/src/main/java/com/padaks/todaktodak/config/WebConfig.java
  member/src/main/java/com/padaks/todaktodak/member/Handler/OAuth2SuccessHandler.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberDto.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  member/src/main/java/com/padaks/todaktodak/member/service/OAuthAttributes.java
  reservation/build.gradle
  reservation/src/main/java/com/padaks/todaktodak/ReservationApplication.java
  reservation/src/main/java/com/padaks/todaktodak/common/config/FeignConfig.java
  reservation/src/main/java/com/padaks/todaktodak/common/config/IamConfig.java
  reservation/src/main/java/com/padaks/todaktodak/configs/JwtAuthFilter.java
  reservation/src/main/java/com/padaks/todaktodak/configs/JwtTokenProvider.java
  reservation/src/main/java/com/padaks/todaktodak/configs/SecurityConfig.java
  reservation/src/main/java/com/padaks/todaktodak/medicalchart/domain/MedicalChart.java
  reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
  reservation/src/main/java/com/padaks/todaktodak/payment/domain/Pay.java
  reservation/src/main/java/com/padaks/todaktodak/payment/domain/Payment.java
  reservation/src/main/java/com/padaks/todaktodak/payment/domain/PaymentStatus.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/MemberDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/PaymentDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/PaymentListDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/PaymentSuccessDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/repository/PaymentRepository.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/MemberFeignClient.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PayMentFeign.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
  reservation/src/main/resources/templates/pay.html
Labels: 기능 구현

#77 feat: 멤버 feign 구현
  member/src/main/java/com/padaks/todaktodak/config/JwtAuthFilter.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/resources/application.yml
  reservation/build.gradle
  reservation/src/main/java/com/padaks/todaktodak/ReservationApplication.java
  reservation/src/main/java/com/padaks/todaktodak/common/config/FeignConfig.java
  reservation/src/main/java/com/padaks/todaktodak/configs/JwtAuthFilter.java
  reservation/src/main/java/com/padaks/todaktodak/configs/JwtTokenProvider.java
  reservation/src/main/java/com/padaks/todaktodak/configs/SecurityConfig.java
  reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
  reservation/src/main/java/com/padaks/todaktodak/payment/domain/Pay.java
  reservation/src/main/java/com/padaks/todaktodak/payment/domain/PaymentMethod.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/PaymentReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/MemberFeignClient.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
  reservation/src/main/resources/application-dev.yml
  reservation/src/main/resources/application.yml
Labels: 기능 구현

#82 feat/IS-49 : fix : Hospital 엔티티, Reservation 엔티티 fk로 연결
  reservation/src/main/java/com/padaks/todaktodak/hospital/domain/Hospital.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
  reservation/src/main/resources/application-dev.yml
Labels: 기능 수정

#83 Feat/IS-48: 알림 crud 기능 생성
  member/.gitignore
  member/src/main/java/com/padaks/todaktodak/notification/controller/NotificationController.java
  member/src/main/java/com/padaks/todaktodak/notification/domain/Notification.java
  member/src/main/java/com/padaks/todaktodak/notification/domain/Type.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationReqDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationResDto.java
  member/src/main/java/com/padaks/todaktodak/notification/repository/NotificationRepository.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationService.java
  member/src/main/resources/application-dev.yml
  member/src/main/resources/application.yml
Labels: 기능 구현

#79 Feat/IS-47: eureka, gateway Dockerfile 작성
  eureka/Dockerfile
  gateway/Dockerfile
Labels: 기능 구현

#87 IS-54 fix:의사정보수정 수정
  hospital/.gradle/8.10/checksums/checksums.lock
  hospital/.gradle/8.10/dependencies-accessors/gc.properties
  hospital/.gradle/8.10/executionHistory/executionHistory.lock
  hospital/.gradle/8.10/fileChanges/last-build.bin
  hospital/.gradle/8.10/fileHashes/fileHashes.bin
  hospital/.gradle/8.10/fileHashes/fileHashes.lock
  hospital/.gradle/8.10/gc.properties
  hospital/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  hospital/.gradle/buildOutputCleanup/cache.properties
  hospital/.gradle/vcs-1/gc.properties
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
Labels: 기능 수정

#88 IS-56 feat:의사 근무시간 생성
  member/src/main/java/com/padaks/todaktodak/common/domain/BaseTimeEntity.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/controller/DoctorOperatingHoursController.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/domain/DoctorOperatingHours.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursReqDto.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursResDto.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursSimpleResDto.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/repository/DoctorOperatingHoursRepository.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java
  member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
Labels: 기능 구현

#90 IS-57 fix : hospital.gradle 삭제, deleteAt 삭제
  hospital/.gradle/8.10/checksums/checksums.lock
  hospital/.gradle/8.10/dependencies-accessors/gc.properties
  hospital/.gradle/8.10/executionHistory/executionHistory.lock
  hospital/.gradle/8.10/fileChanges/last-build.bin
  hospital/.gradle/8.10/fileHashes/fileHashes.bin
  hospital/.gradle/8.10/fileHashes/fileHashes.lock
  hospital/.gradle/8.10/gc.properties
  hospital/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  hospital/.gradle/buildOutputCleanup/cache.properties
  hospital/.gradle/vcs-1/gc.properties
  member/src/main/java/com/padaks/todaktodak/common/domain/BaseTimeEntity.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java
Labels: 기능 수정

#92 merge: main + pay -> 머지 과정 병원 삭제 (2024.09.25 오전 9시 44분)
  member/src/main/java/com/padaks/todaktodak/config/WebConfig.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberPayDto.java
  member/src/main/resources/application.yml
  reservation/build.gradle
  reservation/src/main/java/com/padaks/todaktodak/ReservationApplication.java
  reservation/src/main/java/com/padaks/todaktodak/common/domain/Role.java
  reservation/src/main/java/com/padaks/todaktodak/configs/CorsConfig.java
  reservation/src/main/java/com/padaks/todaktodak/configs/SecurityConfig.java
  reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
  reservation/src/main/java/com/padaks/todaktodak/payment/domain/Pay.java
  reservation/src/main/java/com/padaks/todaktodak/payment/domain/PaymentMethod.java
  reservation/src/main/java/com/padaks/todaktodak/payment/domain/PaymentStatus.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/MemberPayDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/PaymentListDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/PaymentListResDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/dto/PaymentReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/payment/repository/PaymentRepository.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/MemberFeignClient.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
  reservation/src/main/resources/application.yml
Labels: 내부설정 수정

#96 Feat/IS-63 게시판 사진 업로드 수정
  community/build.gradle
  community/src/main/java/com/padaks/todaktodak/CommunityApplication.java
  community/src/main/java/com/padaks/todaktodak/comment/controller/CommentController.java
  community/src/main/java/com/padaks/todaktodak/common/config/CorsConfig.java
  community/src/main/java/com/padaks/todaktodak/common/config/FeignConfig.java
  community/src/main/java/com/padaks/todaktodak/common/config/JwtAuthFilter.java
  community/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
  community/src/main/java/com/padaks/todaktodak/common/feign/MemberFeignClient.java
  community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
  community/src/main/java/com/padaks/todaktodak/post/dto/PostsaveDto.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
  community/src/main/java/com/padaks/todaktodak/report/controller/ReportController.java
  community/src/main/java/com/padaks/todaktodak/report/dto/MemberFeignDto.java
  community/src/main/java/com/padaks/todaktodak/report/dto/ReportSaveReqDto.java
  community/src/main/java/com/padaks/todaktodak/report/service/ReportService.java
  member/build.gradle
  member/src/main/java/com/padaks/todaktodak/MemberApplication.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberReportDto.java
Labels: 기능 수정

#105 IS-64 feat : 사용자에게 fcmToken 저장
  member/build.gradle
  member/src/main/java/com/padaks/todaktodak/config/FcmConfig.java
  member/src/main/java/com/padaks/todaktodak/member/Handler/OAuth2SuccessHandler.java
  member/src/main/java/com/padaks/todaktodak/member/controller/FcmController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/FcmTokenSaveRequest.java
  member/src/main/java/com/padaks/todaktodak/member/service/FcmService.java
Labels: 기능 구현

#110 feat: 결제 자신의 진료내역의 금액만 데이터를 불러오도록 수정 및 코드 개편
  eureka/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberSaveReqDto.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  member/src/main/resources/application.yml
  member/src/main/resources/docker-compose/docker-compose-local.yml
  reservation/src/main/java/com/padaks/todaktodak/medicalchart/service/MedicalChartService.java
  reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
  reservation/src/main/java/com/padaks/todaktodak/payment/repository/PaymentRepository.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
  reservation/src/main/resources/application.yml
Labels: 기능 수정

#107 IS-78 feat: 알림 db 저장 성공
  member/src/main/java/com/padaks/todaktodak/member/service/FcmService.java
Labels: 기능 구현

#109 Fix/is 79 fix : feign, kafka, member-redis 수정
  member/src/main/java/com/padaks/todaktodak/config/RedisConfig.java
  reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/dto/DoctorResDto.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/KafkaReservationConsumerConfig.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/MemberFeign.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationKafkaConsumer.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
Labels: 기능 구현, 기능 수정

#111 Feat/IS-81: firebase realtime DB 연결
  reservation/.gitignore
  reservation/build.gradle
  reservation/src/main/java/com/padaks/todaktodak/common/config/FirebaseConfig.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/Message.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeService.java
Labels: 기능 구현

#114 feat: 결제서비스 + 카프카 붙여서 알림 로직 설정
  eureka/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
  member/build.gradle
  member/src/main/java/com/padaks/todaktodak/common/kafka/KafkaConsumerConfig.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelFailDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentFailDto.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentSuccessDto.java
  member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java
  member/src/main/resources/application-dev.yml
  member/src/main/resources/application.yml
  reservation/build.gradle
  reservation/src/main/java/com/padaks/todaktodak/common/kafka/KafkaConsumerConfig.java
  reservation/src/main/java/com/padaks/todaktodak/common/kafka/KafkaProducerConfig.java
  reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/KafkaReservationConsumerConfig.java
  reservation/src/main/resources/application-dev.yml
  reservation/src/main/resources/application.yml
Labels: 기능 구현, 기능 수정

#115 Feat/is 83 Kafka, Redis를 이용한 스케줄 예약 동시성 처리
  reservation/src/main/java/com/padaks/todaktodak/common/config/RedisConfig.java
  reservation/src/main/java/com/padaks/todaktodak/common/exception/exceptionType/ReservationExceptionType.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/KafkaReservationConsumerConfig.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/KafkaReservationProducerConfig.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationKafkaConsumer.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
  reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationTimeSlot.java
  reservation/src/test/java/com/padaks/todaktodak/ReviewTest.java
Labels: 기능 구현

#117 Feat/IS-70 : stomp 이용한 pub sub 1:1채팅
  community/src/main/java/com/padaks/todaktodak/common/domain/BaseTimeEntity.java
  gateway/src/main/resources/application-dev.yml
  gateway/src/main/resources/application-local.yml
  member/build.gradle
  member/src/main/java/com/padaks/todaktodak/chat/chatmessage/controller/ChatMessageController.java
  member/src/main/java/com/padaks/todaktodak/chat/chatmessage/domain/ChatMessage.java
  member/src/main/java/com/padaks/todaktodak/chat/chatmessage/dto/ChatMessageReqDto.java
  member/src/main/java/com/padaks/todaktodak/chat/chatmessage/dto/ChatMessageResDto.java
  member/src/main/java/com/padaks/todaktodak/chat/chatmessage/repository/ChatMessageRepository.java
  member/src/main/java/com/padaks/todaktodak/chat/chatmessage/service/ChatMessageService.java
  member/src/main/java/com/padaks/todaktodak/chat/chatroom/controller/ChatRoomController.java
  member/src/main/java/com/padaks/todaktodak/chat/chatroom/domain/ChatRoom.java
  member/src/main/java/com/padaks/todaktodak/chat/chatroom/repository/ChatRoomRepository.java
  member/src/main/java/com/padaks/todaktodak/chat/chatroom/service/ChatRoomService.java
  member/src/main/java/com/padaks/todaktodak/chat/controller/ChatController.java
  member/src/main/java/com/padaks/todaktodak/chat/controller/WebSocketController.java
  member/src/main/java/com/padaks/todaktodak/chat/cs/domain/Cs.java
  member/src/main/java/com/padaks/todaktodak/chat/cs/domain/CsStatus.java
  member/src/main/java/com/padaks/todaktodak/chat/cs/dto/CsResDto.java
  member/src/main/java/com/padaks/todaktodak/chat/cs/repository/CsRepository.java
  member/src/main/java/com/padaks/todaktodak/chat/cs/service/CsService.java
  member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java
  member/src/main/java/com/padaks/todaktodak/chat/service/WebSocketService.java
  member/src/main/java/com/padaks/todaktodak/chatmessage/repository/ChatMessageRepository.java
  member/src/main/java/com/padaks/todaktodak/chatroom/repository/ChatRoomRepository.java
  member/src/main/java/com/padaks/todaktodak/common/domain/BaseTimeEntity.java
  member/src/main/java/com/padaks/todaktodak/common/exception/BaseException.java
  member/src/main/java/com/padaks/todaktodak/common/exception/exceptionType/ChatExceptionType.java
  member/src/main/java/com/padaks/todaktodak/config/JwtTokenProvider.java
  member/src/main/java/com/padaks/todaktodak/config/StompHandler.java
  member/src/main/java/com/padaks/todaktodak/config/WebSocketConfig.java
  member/src/main/java/com/padaks/todaktodak/cs/domain/CsStatus.java
  member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/controller/DoctorOperatingHoursController.java
  member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
  reservation/build.gradle
  reservation/src/main/java/com/padaks/todaktodak/common/domain/BaseTimeEntity.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalDTO/HospitalAndAdminRegisterReqDto.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalDTO/HospitalAndAdminRegisterResDto.java
  reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
Labels: 기능 구현

#118 IS78 Feat/is 78 - FCM 게시판 알림
  community/build.gradle
  community/src/main/java/com/padaks/todaktodak/comment/domain/Comment.java
  community/src/main/java/com/padaks/todaktodak/comment/dto/CommentReqDto.java
  community/src/main/java/com/padaks/todaktodak/comment/dto/CommentSaveDto.java
  community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
  community/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignDto.java
  community/src/main/java/com/padaks/todaktodak/common/feign/MemberFeignClient.java
  community/src/main/java/com/padaks/todaktodak/common/kafka/KafkaConsumerConfig.java
  community/src/main/java/com/padaks/todaktodak/common/kafka/KafkaProducerConfig.java
  community/src/main/java/com/padaks/todaktodak/communitynotification/controller/NotificationController.java
  community/src/main/java/com/padaks/todaktodak/communitynotification/controller/SseController.java
  community/src/main/java/com/padaks/todaktodak/communitynotification/domain/Notification.java
  community/src/main/java/com/padaks/todaktodak/communitynotification/dto/NotificationListDto.java
  community/src/main/java/com/padaks/todaktodak/communitynotification/repository/NotificationRepository.java
  community/src/main/java/com/padaks/todaktodak/communitynotification/service/NotificationService.java
  community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
  community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
  community/src/main/java/com/padaks/todaktodak/report/controller/ReportController.java
  community/src/main/java/com/padaks/todaktodak/report/service/ReportService.java
  gateway/build.gradle
  member/.gitignore
  member/build.gradle
  member/src/main/java/com/padaks/todaktodak/common/service/InitialDataLoader.java
  member/src/main/java/com/padaks/todaktodak/member/controller/FcmController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/AdminSaveDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/DoctorAdminSaveReqDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/DoctorSaveReqDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberListResDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberLoginDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberSaveReqDto.java
  member/src/main/java/com/padaks/todaktodak/member/service/FcmService.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  member/src/main/java/com/padaks/todaktodak/notification/domain/Notification.java
  member/src/main/java/com/padaks/todaktodak/notification/domain/Type.java
  member/src/main/java/com/padaks/todaktodak/notification/dto/CommentSuccessDto.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
  member/src/main/java/com/padaks/todaktodak/notification/service/NotificationService.java
  reservation/src/main/java/com/padaks/todaktodak/common/config/FirebaseConfig.java
Labels: 기능 구현

#119 chore: 멤버 프론트 부분 수정을 위한 백엔드 코드 수정
  member/src/main/java/com/padaks/todaktodak/config/StompHandler.java
  member/src/main/java/com/padaks/todaktodak/member/Handler/OAuth2SuccessHandler.java
  member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
  member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberFindIdDto.java
  member/src/main/java/com/padaks/todaktodak/member/dto/MemberUpdateReqDto.java
  member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
  member/src/main/java/com/padaks/todaktodak/member/service/CustomOAuth2UserService.java
  member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
  member/src/main/java/com/padaks/todaktodak/member/service/OAuthAttributes.java
  reservation/src/main/resources/application.yml
Labels: 기능 구현, 기능 수정
